### ISSUE TITLE
Add default transmit functionality

### ISSUE THREAD

**Issue by danehammer** [SquareSquash/java#1]
The README shows an example that assumes you use Gson to serialize the SquashEntry and transmit it to the squash web service. When getting started using this, it'd be nice to have a class that would do that Gson and transmission work for you.

**Comment by JakeWharton** [comment]
Serialization and transmission should be a fairly straightforward process. Since this library can be used on the JVM as well as on Android we don't want to make any assumptions as to what serialization library nor HTTP library the client would be using.

If you're using GSON and an implementation of Apache's `HttpClient` it should be as simple as:

``` java
HttpPost p = new HttpPost("http://path/to/squash/endpoint");
p.setEntity(new StringEntity(gson.toJson(entry), "UTF-8"));
client.execute(p);
```

**Comment by danehammer** [comment]
Okay thanks. Took me a little longer to recreate that snippet, but that's where I'm at now. :smile:

**Comment by rouvoy** [comment]
Well, this is definitively disappointing as one could use the JSR-330 to inject the HTTP client handler depending on the execution environment (JVM Vs. Android)...

**Comment by monperrus** [comment]
I was convinced that squash-java encapsulates the communication with the server. It took us long minutes to understand that it's not the case.  

IMHO, the standard transmit code (JVM+GSON) should be included by default (maybe in a documented separate branch).

Best regards, --Martin
